name: Check
on: [ pull_request, push ]
jobs:
  check:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Test & Coverage
        run: ./gradlew test --no-daemon
      - name: Upload to Codecov
        if: ${{ matrix.java == '21' }} # Upload from a single matrix instance
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
      - name: Upload artifacts
        if: ${{ matrix.java == '21' }} # Upload from a single matrix instance
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/*
